---
- hosts: web
  user: ec2-user
  sudo: true

  # vars:
  #   pick name: telnet

  tasks:
  # - name install {{ pack_name}}
  #  yum: pkg={{ pack name }} state=absent
  #  register: xyz
  #  debug: var=xyz.stdout
   - name: "print date"
     shell: date
     register: xyz
   - debug: var=xyz
   - lineinfile:
       
path: /opt/ansible-demo/xyz.stdout
       line: "{{ xyz.stdout }}"
       state: present
       create: yes


   - name: "uptime"
     shell: uptime
     register: xyz
   - debug: var=xyz

   - name: "/etc/hosts"
     shell: cat /etc/hosts
     register: output
   - debug: var=output
